import unittest
import pytest
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.action_chains import ActionChains
from datetime import date
import parameterized
import time
import basetest
import common_steps as step, common_steps as When, common_steps as And, common_steps as Then, common_steps as Given

ToS = ('Please read these Terms of Service (“Terms of Service”',
    '1.	ACCOUNTS AND LICENSE',
       'a.	Description and License. LINQ Connect is an online management and payment solution that provides ',
       'authorized registered parents, guardians, faculty, staff, and their designees (“Users”) who are legally ',
       'associated with a student, staff, or faculty member (“Student”) associated with a participating school ',
       'or school district (“School”) with the ability to access their Student’s account information, ',
       'view purchase history, add funds to an account, make a payment, and manage their own LINQ Connect ',
       'account through the LINQ Connect website, the LINQ Connect mobile app, or other authorized access ',
       'methods (collectively “Services”).  Certain portions of the Services, specifically event schedules, tickets,',
       ' menus, and nutritional information (“Public Items”) may be available to individuals not associated with a ',
       'Student (“Public Users”). LINQ grants Users and Public Users a limited, non-exclusive, non-transferrable ',
       'license to access and make personal use of the Services and Information, to establish an account, to review ',
       'Information, to make payments for available goods and services, create an account, and other supported ',
       'functionality. Users may also be able to use the Services to obtain information about the balance of their ',
       'Student’s account and to review purchases. LINQ may, in our sole discretion and without notice, revoke license ',
       'and access of a User or Public User at any time based on our reasonable discretion. Certain Services are ',
       'intended to be used by adults who can make purchases with a credit card, a debit card, or from a U.S. bank ',
       'account. Services are not intended for use by individuals under the age of 18. ',
       'b.	Reliance. LINQ endeavors to provide timely, accurate and complete information.  To accomplish this, ',
       'we work with schools, school districts, and third-party companies to provide the information offered through ',
       'the Services. Since LINQ is not in control of all systems, information, or transmission mechanisms, you agree ',
       'that LINQ is not responsible for any loss or damages caused or alleged to have been caused by the use of or ',
       'reliance on Services or content. Menus, ingredients, and other elements may be changed by the School without ',
       'notice. You acknowledge and agree that LINQ is not responsible for the timeliness or accuracy of information ',
       'because the content is provided by the School or third-parties, and the accuracy of the content may be outside ',
       'of LINQ’s control. If you believe there is a risk of injury or harm, you are advised to contact the school or ',
       'district directly and discuss the matter with the appropriate staff. ',
       'c.	Account Credentials. To access the Services, excluding certain Public Items, you must first establish ',
       'LINQ Connect access credentials (e.g., a username and password) that enable you to log into and use the ',
       'Services (“Credentials”). Your Credentials enable LINQ to authenticate you as an authorized user of the ',
       'Services and to provide appropriate authorizations regarding the scope of use of the Services. You are ',
       'solely responsible for maintaining the confidentiality and security of your Credentials, and agree to be ',
       'responsible for maintaining the confidentiality and security of your Credentials. Do not share Credentials ',
       'with anyone. LINQ will not contact you to request account or payment information, though we may verify your ',
       'account details if you contact us. If you receive communication from anyone representing themselves as LINQ, ',
       'please only respond to emails from linq.com or linqconnect.com and only call the phone number on our website. ',
       'You are responsible for any use of or access to the Services and use of your Credentials. If you become aware ',
       'of any unauthorized use of or compromise of Credentials, you must notify LINQ immediately. ',
       'd.	Account Functionality. Depending on the Services permitted by your School, you may be able to add funds ',
       'to your Student’s account, pay invoices, make purchases in school stores, see purchase and payment history, ',
       'transfer meal funds between students, submit school forms, receive notifications on low account balances and ',
       'pending invoices, receive School communications, view meal menus, check registration status, order meals, make ',
       'donations, and perform other activities. Account functionality may vary by student, school or school district. ',
       'e.	Updates. From time to time, in our sole discretion, LINQ may make available updates, bug fixes, upgrades, ',
       'patches and/or new versions of the Services (collectively, “Updates”). You agree to promptly install Updates ',
       'to the LINQ Connect mobile application when they become available. You understand and agree that Updates may ',
       'include necessary functionality and/or fixes to protect the security of the Services and that your failure to ',
       'promptly install such Updates may compromise your ability to use the Services and/or result in the disabling ',
       'of your Credentials. LINQ shall have no liability to you for any loss or damage resulting from your failure ',
       'to timely accept such Updates.',
       '2.	PRIVACY POLICY. LINQ’s Privacy Policy applies to use of this Site, and its terms are made a part of these ',
       'Terms of Use by this reference. To view LINQ’s Privacy Policy, click here. We reserve the right to update the ',
       'Privacy Policy from time-to-time.',
       '3.	MAKING A PAYMENT. ',
       'a.	LINQ Connect allows Users to make payments into their Student’s school account or to pay an invoiced fee ',
       'using either a payment card or electronic check. LINQ Connect may allow Public Users to make donations and ',
       'pay for events and tickets. LINQ may charge a Fee in connection with the Services and/or transactions ',
       'processed through the Services (“Fee”). If a Fee is charged, the amount of the Fee will be displayed ',
       'onscreen before you complete the payment transaction and will apply to each one-time, automated, and ',
       'scheduled payment. By requesting a payment transaction, you are agreeing to pay the Fee to LINQ. In ',
       'certain cases, the School may cover all or part of the Fee.',
       'b.	Payment Options. LINQ Connect supports one-time, scheduled, and automated payments:',
       'i.	One-time payments. If you requested a one-time payment, you authorize LINQ to debit the bank account or ',
       'payment card as indicated on your payment request for the amount listed. You understand that because this is ',
       'an electronic transaction, funds may be withdrawn from your account immediately. You acknowledge that by ',
       'using an electronic check or ACH for a transaction, you must comply with U.S. law. You will not try to ',
       'prevent LINQ from debiting your bank account or payment card, and you acknowledge that any dispute is limited ',
       'to errors that LINQ made in processing. LINQ does not have any responsibility for information that you ',
       'entered incorrectly.',
       'ii.	Scheduled payments. LINQ Connect provides the ability to select scheduled payments that can be used ',
       'to add money to your Student’s designated account based on a permitted schedule (collectively, “Scheduled ',
       'Payment”). If you enabled one or more Scheduled Payment methods, you authorize LINQ to debit the bank ',
       'account or payment card indicated through the Service for the specified amount, including our Fee, based ',
       'on the conditions specified. You understand that this authorization will remain in effect until the ',
       'scheduled end date, or until you cancel the payment, whichever comes first. ',
       'iii.	Automated payments. LINQ Connect provides the ability to select automated payments that can be used to ',
       'add money to your Student’s designated account when a condition that you specify, such as a low balance, is ',
       'achieved (collectively, “Automated Payment”). If you enabled one or more Automated Payment methods, you ',
       'authorize LINQ to debit the bank account or payment card as you indicated through the Service for the ',
       'specified amount, including our Fee, based on the conditions specified. You understand that this authorization ',
       'will remain in effect until the scheduled end date, or until you cancel the payment, whichever comes first. ',
       'iv.	Holidays. If a Scheduled Payment or an Automated Payment falls on a holiday or non-banking day, you ',
       'understand that the payment may be executed on the next business day. You understand that because this is ',
       'an electronic transaction, funds may be withdrawn from your bank account or applied to your payment card, ',
       'as you specified.',
       'c.	Failed payments. If your payment transaction fails for any reason, you authorize LINQ to reverse the ',
       'provisional credit applied to your Student’s account and deducted from your Student’s account without notice. ',
       'If the purchase is related to a Student fee, event, activity, or ticket that cannot be recovered, LINQ and/or ',
       'the School or a designee may use any legal means available to seek recovery of the failed payment. ',
       'd.	Transferring funds between accounts. Users with more than one Student associated with their account may ',
       'be permitted to transfer funds from one Student to another Student. By using this feature, you certify that ',
       'you are legally authorized to access each Student’s account and transfer funds.',
       'e.	Limitations. Your payment card provider or bank may place limitations on your payments. You agree to only ',
       'use a payment card or U.S. bank account to which you have authorized use. You understand that LINQ may charge ',
       'a Fee as a result of your payment request, and you agree you will not try to prevent LINQ from fulfilling the ',
       'payment. You agree that any dispute is limited to any errors that LINQ made in processing. LINQ does not have ',
       'any responsibility for information that you entered incorrectly. ',
       'f.	Potential Delays. While LINQ Connect works diligently to process each payment and apply the credit to ',
       'your Student’s account in a timely manner, we make no representations or warranties regarding the amount of ',
       'time needed to complete processing payments through LINQ Connect or your Student’s School since factors, ',
       'such as delays in the banking system, electronic funds transfer systems or School network, are outside our ',
       'control and will affect when the funds are received by your Student’s School. School’s use of payments or ',
       'prepayments is governed by your agreement or arrangement with the School, and LINQ is not responsible for ',
       'the School’s handling of your payments or prepayments after the School receives the funds from the Services, ',
       'including, but not limited to, any failure by a School to record, apply, transfer, or refund a payment made ',
       'using the Services.',
       'g.	ACH or Electronic Check Payments. You acknowledge that by using an electronic check or ACH payment, you ',
       'must comply with U.S. law, and you explicitly agree to waive any pre-notification requirements and acknowledge ',
       'that you explicitly authorize LINQ to process the payment transaction in accordance with your most current ',
       'payment instructions.',
       '4.	REFUNDS.',
       'a.	If you are not satisfied with any good or service purchased using the Services, you agree to resolve ',
       'the issue exclusively with the School or third-party that provided the good or service. You agree that you ',
       'will not seek and are not entitled to a refund of any amount from LINQ. If you would like a refund of any ',
       'kind from the School, you must contact the School directly. Refund policies may vary by the School and cannot ',
       'be controlled by LINQ. ',
       'b.	Unless otherwise stated, all payments for activities, events, and tickets are non-refundable. You may ',
       'contact the School or third-party seller to inquire about any changes to the schedule, postponement, ',
       'cancellation, or possible refund from the School or third-party seller.',
       'c.	LINQ’s Fees are not refundable, and you agree that you will not seek and are not entitled to a ',
       'full or partial refund of any Fee. LINQ provides a service that is fulfilled when we process or attempt ',
       'to process your payment request, whether one-time or a recurring basis. Once a payment request is fulfilled ',
       'and a notice is sent to the indicated School, LINQ’s obligation has been fulfilled. ',
       '5.	COMMUNICATIONS.',
       'a.	Please use the online tools in LINQ Connect if you need assistance resetting a password or access ',
       'functionality.',
       'b.	When you visit the LINQ Connect website, use the LINQ Connect mobile application, or send emails to ',
       'us, you are communicating with us electronically. You consent to receive communications from us electronically. ',
       'We may communicate with you by email, text message, or posting notices on this website or in the mobile ',
       'application. You agree that all agreements, notices, disclosures and other communications that we provide ',
       'to you electronically satisfy any legal requirement that such communications be in writing.',
       'c.	Our Customer Support team is available through the Contact Us chat feature on LINQ Connect or by ',
       'email at support@linqconnect.com. If you have questions about your Student’s purchases, account, status, ',
       'health, or other similar information, we recommend you contact your Student’s School directly. LINQ’s ',
       'Customer Support team cannot provide any information about Students or accounts; please contact the School ',
       'directly. ',
       'd.	You may have the opportunity to opt-in to receiving SMS communications through the Service. If enabled, ',
       'we may send messages regarding low balance alerts, password resets, additional services, and other account ',
       'activities. You can cancel the SMS service at any time through your account or by texting “STOP” to the short ',
       'code. Message and data rates may apply for any messages sent to you from us and to us from you. The frequency ',
       'of messages varies by account. If you have any questions about your text or SMS plan or data plan, we ',
       'recommend you contact your wireless provider.',
       '6.	YOUR USE OF LINQ CONNECT.',
       'a.	Content, Images & Marks. All content, titles, graphics, logos, button icons, text, images and software ',
       '(“Content”) are the copyrighted material of LINQ, or its licensors, and you agree not to download (other than ',
       'page caching) or modify it, or any portion of it. The compilation of all Content on the LINQ Connect website ',
       'and the LINQ Connect mobile application is the exclusive property of LINQ and is protected by U.S. and ',
       'international copyright laws. Reproduction, republication or distribution of any material from the website ',
       'is strictly prohibited, except that you may, for personal and non-commercial use only, make a single hard ',
       'copy of your transactions for your personal records.',
       'b.	Delivery Policy. LINQ operates as a service provider to the School, and the School is solely responsible ',
       'for the delivery or fulfillment of any order placed. In general, goods and services offered by Schools on ',
       'LINQ Connect are not delivered unless delivery information is specifically listed in the item, in which case ',
       'the fulfillment is between you and the School. You agree that LINQ has no responsibility related to fulfillment ',
       'of delivery beyond notifying the School of a successful payment.',
       'c.	Access Limitations. You may not use any “deep-link”, “page-scrape”, “robot”, “spider” or other automatic ',
       'device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, ',
       'copy or monitor any portion of the Services or any Content, or in any way reproduce or circumvent the ',
       'navigational structure or presentation of the Services or any Content, to obtain or attempt to obtain ',
       'any materials, documents or information through any means not purposely made available through the Services. ',
       'LINQ reserves the right to bar any such activity. You may not attempt to gain unauthorized access to any ',
       'portion or feature of the Services, or any other systems or networks connected to the Site or to any LINQ ',
       'server, or to any of the services offered on or through the Site, by hacking, password “mining” or any other ',
       'illegitimate means. You may not probe, scan or test the vulnerability of the Services or any network connected ',
       'to the Services, nor breach the security or authentication measures on the Services or any network connected ',
       'to the Services. You may not reverse look-up, trace or seek to trace any information on any other user of or ',
       'visitor to the Services, or any other customer of LINQ, including any LINQ Connect account not owned by you, ',
       'to its source, or exploit the Services or any service or information made available or offered by or through ',
       'the Services, in any way where the purpose is to reveal any information, including but not limited to personal ',
       'identification or information, other than your own information, as provided for by the Services. You agree ',
       'that you will not take any action that imposes an unreasonable or disproportionately large load on the ',
       'infrastructure of the Services or LINQ’s systems or networks, or any systems or networks connected to ',
       'the Services or to LINQ Connect.',
       '7.	SECURITY.',
       'a.	Secure Checkout Policy. When you place orders through the LINQ Connect websites or mobile application, ',
       'all of your payment information, including your card or account information and address, is transmitted ',
       'through the Internet using Secure Sockets Layer (SSL) technology. SSL technology causes your browser to ',
       'encrypt your order information before transmitting it to our secure server. SSL technology, an industry ',
       'standard, is designed to prevent someone other than operators of our websites from capturing and viewing ',
       'your personal information. While we use industry-standard means to protect our Services and your ',
       'information, the Internet is not 100% secure. The measures we use are appropriate for the type of ',
       'information we collect. We cannot promise that your use of our websites or mobile applications will ',
       'be completely safe. We encourage you to use caution when using the Internet. Online access to your personal ',
       'information is protected with Credentials you select. We strongly recommend that you do not share your ',
       'password and that you use unique passwords for all your online accounts.',
       'b.	Student Accounts. Each School defines the fields and data required to add a student or staff member ',
       'to your account. It is strongly recommended that you and your student protect any information that could ',
       'be used to access account information. If you suspect that your student is attached to an unauthorized ',
       'account or experiences unauthorized activity, you should contact either LINQ’s Customer Support or your ',
       'student’s school immediately.',
       'c.	Links to Other Websites. LINQ Connect, through our websites and mobile applications, may contain ',
       'links to websites, mobile applications, social media platforms, and other materials that are owned, operated, ',
       'or managed by others. LINQ does not maintain, control, or endorse such websites, applications, platforms, or ',
       'materials, nor has LINQ reviewed or approved any content that appears on such other websites or applications. ',
       'You acknowledge and agree that we will not be held responsible for the legitimacy, legality, accuracy, or ',
       'inappropriate nature of any content, advertisements, endorsements, products, services, or information located ',
       'on or through any other websites or mobile applications, nor for any loss, harm, or damages caused or alleged ',
       'to have been caused by the use of or reliance on such content.',
       '8.	TRADEMARKS. The LINQ Connect name, logo, button icons, color combination, characters, trade dress, and all ',
       'related logos, products and services described in the LINQ Connect website and the LINQ Connect mobile ',
       'application, as well as the LINQ name and logo (collectively, “Marks”), are trademarks or registered trademarks ',
       'of EMS LINQ, Inc. The LINQ Connect name is a registered trademark of EMS LINQ, Inc. All other trademarks that ',
       'appear on the LINQ Connect website and the LINQ Connect mobile application that are not owned by LINQ or our ',
       'affiliates are the property of their respective owners.',
       '9.	LIMITED LIABILITY AND DISCLAIMER OF WARRANTY.',
       'a.	THE SERVICES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. LINQ MAKES NO WARRANTY THAT THE SERVICES ',
       'WILL BE UNINTERRUPTED, ERROR FREE OR FREE FROM VIRUSES OR OTHER DEFECTS OR HARMFUL COMPONENTS, NOR DO WE MAKE ',
       'ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SERVICES, OR AS TO THE ACCURACY, ',
       'RELIABILITY OR CONTENT OF ANY INFORMATION PROVIDED THROUGH THE SERVICES. LINQ MAKES NO WARRANTIES OF ANY KIND, ',
       'EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF TITLE, NONINFRINGEMENT, OR IMPLIED WARRANTIES ',
       'OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. YOU EXPRESSLY AGREE THAT THE USE OF THE SERVICES IS AT ',
       'YOUR SOLE RISK.',
       'b.	LINQ CONNECT IS NOT THE ONLY WAY TO MAKE PAYMENTS TO YOUR SCHOOL. THUS, IF YOU DO NOT AGREE TO THESE TERMS ',
       'CONTAINED HEREIN, YOU SHOULD NOT USE LINQ CONNECT FOR ANY PURPOSE. IN THE EVENT LINQ CONNECT IS NOT AVAILABLE ',
       'AT ANY TIME FOR ANY REASON, YOU AGREE TO CONTACT YOUR STUDENT’S SCHOOL TO MAKE ALTERNATIVE PAYMENT ARRANGEMENTS. ',
       'LINQ IS NOT RESPONSIBLE FOR THE CONSEQUENCES OF ANY FAILURE BY THE SCHOOL TO RECEIVE OR PROPERLY APPLY ANY PAYMENT.',
       'c.	TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, LINQ, ON BEHALF OF ITSELF AND ITS AFFILIATES, DISCLAIMS ',
       'ALL LIABILITY FOR ANY CLAIMS, LOSSES, ACTIONS, DAMAGES OR INJURY RESULTING FROM ANY FAILURE OF PERFORMANCE ',
       'OF THE SERVICES, ERRORS, OMISSIONS, INACCURACIES, INTERRUPTIONS, DEFECTS, DELAYS OR INTERRUPTIONS IN ',
       'OPERATION OR TRANSMISSION, COMMUNICATION LINE FAILURE, SECURITY BREACH, UNAUTHORIZED ACCESS TO, ALTERATION ',
       'OF OR USE OF INFORMATION. IN NO EVENT SHALL LINQ, OR ITS AFFILIATES, BE LIABLE FOR ANY DAMAGES OF ANY KIND ',
       'ARISING OUT OF THE USE OR INABILITY TO USE THE SERVICES, INCLUDING, BUT NOT LIMITED TO, DIRECT, INDIRECT, ',
       'INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES. CERTAIN STATES DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES ',
       'OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS OR ',
       'LIMITATIONS MAY NOT APPLY TO YOU.',
       'd.	YOU AGREE THAT IN NO EVENT WILL LINQ BE LIABLE FOR ANY CLAIM, BILLING ERROR, CHARGE, DAMAGE, OR EXPENSE ',
       'ARISING OUT OF OR RELATING IN ANY WAY TO THESE TERMS OF SERVICE, THE USE OF LINQ CONNECT OR ANY TRANSACTION ',
       'PROCESSED WITH OR THROUGH LINQ CONNECT IF YOU DO NOT REPORT THE CLAIM, ERROR, CHARGE, DAMAGE, OR EXPENSE TO ',
       'LINQ IN WRITING WITHIN 90 DAYS OF THE ALLEGEDLY WRONGFUL ACT OR FAILURE TO ACT, OR, IN THE EVENT OF A BILLING ',
       'OR PAYMENT ERROR OR OVERCHARGE, WITHIN 90 DAYS OF THE DATE THAT THE STATEMENT CONTAINING THE CHARGE WAS MADE ',
       'AVAILABLE TO YOU ELECTRONICALLY OR IN HARD COPY. YOU EXPRESSLY WAIVE ANY CLAIM THAT IS NOT REPORTED TO LINQ ',
       'IN WRITING WITHIN THE TIME PERIODS STATED HEREIN.',
       '10.	APPLICABLE LAW. By visiting LINQ Connect, using the website, accessing the mobile application, or using ',
       'our Services, you agree to that the laws of the State of North Carolina will govern these Terms.',
       '11.	MODIFICATION. We reserve the right at any time and from time to time to modify, discontinue, temporarily ',
       'or permanently, the Service (or any part thereof) with or without notice. You agree that LINQ shall not be ',
       'liable to you or to any third party for any modification, suspension or discontinuance of the Service or any ',
       'portion thereof.',
       '12.	TERMINATION AND CANCELLATION. Either you, LINQ or a School may terminate or cancel the Service at any ',
       'time. You understand and agree that the cancellation of your User account is your sole right and remedy with ',
       'respect to any dispute with LINQ. This includes, but is not limited to, any dispute related to, or arising ',
       'out of: (1) any term of this Agreement or our enforcement or application of any such term; (2) any policy or ',
       'practice of LINQ, including our Privacy Policy or our enforcement or application of these policies; (3) the ',
       'Content; or (4) the amount or type of Fee, applicable taxes, billing methods, or any change to the Fee, ',
       'applicable taxes, surcharges or billing methods. All other provisions of these Terms which may reasonably ',
       'be construed as surviving such termination will survive the termination of this Agreement, including, but ',
       'not limited to paragraphs 1, 2, 3, 4, 8, 9, 10, and 13.',
       '13.	ENTIRE AGREEMENT. These Terms are the entire agreement between you and LINQ with respect to use of the ',
       'Services, and supersede all previous written or oral agreements between the parties with respect to such ',
       'subject matter. Other than with respect to Section 10, LINQ reserves the right at any time to change, add ',
       'or delete any aspect or feature of the Services and these Terms, including but not limited to, changing ',
       'program fees. LINQ will provide notice of any such change by posting a notice to the website or as otherwise ',
       'required by law. Any use of the Services by you after such notice has been posted or otherwise communicated ',
       'will be deemed acceptance by you of such changes. Any waiver of LINQ’ rights must be in writing and signed by ',
       'LINQ. Except as expressly stated in Section 14, should any provision of this Agreement be held invalid or ',
       'unenforceable by any court of competent jurisdiction, the remaining provisions shall remain in full force ',
       'and effect.'
       );

ToS2 = ('')

class MyTestCase(basetest.testFixture):
    @pytest.mark.tos
    def test_ToS(self):
        When.log_into_Test(self.driver);
        And.click_on(self.driver, 'global-header-hamburger-button');
        And.click_on(self.driver, 'termsOfServiceButton');
        text = self.driver.find_element(By.TAG_NAME, 'linq-dialog')
        print(text.text);
        #Then.should_see_text(self.driver, 'unenforceable by any court of competent jurisdiction')
        #for i in ToS:
        #    print(i);
        #    Then.should_see_text(self.driver, i);


if __name__ == '__main__':
    unittest.main()
